language: generic
script:
- make ci

branches:
  only:
  - master

before_deploy:
- openssl aes-256-cbc -K $encrypted_a80edde55186_key -iv $encrypted_a80edde55186_iv -in deploy_key.enc -out deploy_key -d

deploy:
  provider: pages
  local_dir: out
  deploy_key: deploy_key
  edge:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
